[tool.poetry]
name = "year-service"
version = "0.1.0"
description = ""
authors = ["Honeycomb"]

[tool.poetry.dependencies]
python = "^3.10"
honeycomb-beeline = "^3.5.1"
django = "^4.1.9"
python-dotenv = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
autopep8 = "^2.0.1"
