version: "2.4"

x-common-env: &common-env
  OTEL_EXPERIMENTAL_CONFIG_FILE: /otelconf.yaml
  HONEYCOMB_API_KEY: ${HONEYCOMB_API_KEY}
  OTEL_EXPORTER_OTLP_ENDPOINT: https://api.honeycomb.io
  OTEL_RESOURCE_ATTRIBUTES: app.running-in=docker
  MESSAGE_ENDPOINT: http://message:9000
  NAME_ENDPOINT: http://name:8000
  YEAR_ENDPOINT: http://year:6001
  REDIS_URL: redis

services:
  frontend:
    build:
        context: .
        dockerfile: ./frontend/Dockerfile
    image: hnyexample/frontend-golang
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: frontend-go
    ports:
      - 7777:7777
    volumes:
      - ../otelconf.yaml:/otelconf.yaml:ro

  message:
    build:
        context: .
        dockerfile: ./message-service/Dockerfile
    image: hnyexample/message-golang
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: message-go
    ports:
      - 9000:9000
    volumes:
      - ../otelconf.yaml:/otelconf.yaml:ro

  name:
    build:
        context: .
        dockerfile: ./name-service/Dockerfile
    image: hnyexample/name-golang
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: name-go
    ports:
      - 8000:8000
    volumes:
      - ../otelconf.yaml:/otelconf.yaml:ro

  year:
    build:
        context: .
        dockerfile: ./year-service/Dockerfile
    image: hnyexample/year-golang
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: year-go
    ports:
      - 6001:6001
    volumes:
      - ../otelconf.yaml:/otelconf.yaml:ro

  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"

