[tool.poetry]
name = "name-service"
version = "0.1.0"
description = ""
authors = ["Honeycomb"]

[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.2.3"
python-dotenv = "^1.0.0"
requests = "^2.28.2"
opentelemetry-api = "^1.16.0"
opentelemetry-sdk = "^1.16.0"
opentelemetry-exporter-otlp-proto-grpc = "^1.16.0"
opentelemetry-instrumentation-flask = "^0.37b0"
opentelemetry-instrumentation-requests = "^0.37b0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
autopep8 = "^2.0.1"
